AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Order capture and tracking API
  
Globals:
  Function:
    Timeout: 3

# ====================================================================
#                     PARAMETERS
# ====================================================================

Parameters:
  OrderTableName:
    Type: String
    Description: "Order table name"
    AllowedPattern: ".+"

# ====================================================================
#                     Resources
# ====================================================================

Resources:
  # ========================== POLICIES ================================
  OrderCaptureAccessLogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AccessLog
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "logs:*"
            Resource: "arn:aws:logs:*:*:*"
      Roles:
        - !Ref OrderAPIGatewayRole
        - !Ref AccountAPIGatewayRole
        - !Ref StockAPIGatewayRole
        - !Ref BalanceCheckerRole
        - !Ref StockCheckerRole
        - !Ref OrderUpdateRole
        - !Ref ShipOrderRole

  OrderDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "order-table-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:BatchGetItem
              - dynamodb:DescribeTable
            Resource: 
              - !GetAtt OrderDynamoDBTable.Arn
      Roles:
        - !Ref OrderAPIGatewayRole
        - !Ref OrderUpdateRole
        - !Ref ShipOrderRole

  AccountUpdateDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "account-update-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - dynamodb:PutItem
            Resource: 
              - !GetAtt AccountDynamoDBTable.Arn
      Roles:
        - !Ref AccountAPIGatewayRole
        - !Ref ShipOrderRole

  BalanceDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "balance-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:BatchGetItem
              - dynamodb:DescribeTable
            Resource: 
              - !GetAtt AccountDynamoDBTable.Arn
      Roles:
        - !Ref BalanceCheckerRole
        - !Ref ShipOrderRole

  StockUpdateDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "stock-table-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - dynamodb:PutItem
            Resource: 
              - !GetAtt StockDynamoDBTable.Arn
      Roles:
        - !Ref StockAPIGatewayRole
        - !Ref ShipOrderRole

  StockCheckDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "stock-check-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:BatchGetItem
              - dynamodb:DescribeTable
            Resource: 
              - !GetAtt StockDynamoDBTable.Arn
      Roles:
        - !Ref StockCheckerRole
        - !Ref ShipOrderRole

  OrderTopicPolicy:
    Type: AWS::IAM::Policy
    DependsOn: OrderTopic
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "order-topic-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - sns:Publish
            Resource: !Ref OrderTopic 
      Roles:
        - !Ref OrderAPIGatewayRole

  BalanceCheckerQueryPolicy:
    Type: AWS::IAM::Policy
    DependsOn: BalanceCheckerQueue
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "balance-checker-queue-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt BalanceCheckerQueue.Arn 
      Roles:
        - !Ref BalanceCheckerRole

  StockCheckerQueryPolicy:
    Type: AWS::IAM::Policy
    DependsOn: StockCheckerQueue
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "stock-checker-queue-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt StockCheckerQueue.Arn 
      Roles:
        - !Ref StockCheckerRole

  OrderUpdateProducePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "update-order-produce-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - sqs:SendMessage
            Resource: !GetAtt OrderUpdateQueue.Arn 
      Roles:
        - !Ref BalanceCheckerRole
        - !Ref StockCheckerRole

  OrderUpdateConsumerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Join ["-", [!Ref AWS::StackName, "update-order-consumer-policy"]]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: 
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt OrderUpdateQueue.Arn 
      Roles:
        - !Ref OrderUpdateRole

  # ========================== ROLES ================================ 
  OrderAPIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "gateway-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  AccountAPIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "account-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  BalanceCheckerRole:
    Type: AWS::IAM::Role
    DependsOn: BalanceCheckerQueue
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "balance-checker-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  StockAPIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "stock-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  StockCheckerRole:
    Type: AWS::IAM::Role
    DependsOn: StockCheckerQueue
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "stock-checker-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  OrderUpdateRole:
    Type: AWS::IAM::Role
    DependsOn: OrderUpdateQueue
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "order-update-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  ShipOrderRole:
    Type: AWS::IAM::Role
    DependsOn: OrderUpdateQueue
    Properties:
      RoleName: !Join ["-", [!Ref AWS::StackName, "ship-order-lambda-role"]]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
      Path: /

  # ========================== API GATEWAY ================================
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join ["-", [!Ref AWS::StackName, "api-gateway"]]
      StageName: Staging
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiGatewayApi
    Properties:
      UsagePlanName: 
        !Join ["-", [!Ref AWS::StackName, "usage-plan"]] 
      ApiStages: 
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref ApiGatewayApi.Stage
      Description: ApiUsagePlan is not mandatory to this assignment. It is good to have and limit the usage.
      Quota: # Quota makes the api looks expensive to use. It is use protect my wallet.
        Limit: 10000
        Period: WEEK
      Throttle:
        BurstLimit: 1000
        RateLimit: 1000

  # ========================== Queue =================================
  BalanceCheckerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, "balance-checker-queue"]]
      VisibilityTimeout: 300 # Wait for 5 minutes after previous attempt fail
      MessageRetentionPeriod: 3600 # Decrease message expire to 1 hours 

  StockCheckerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, "stock-checker-queue"]]
      VisibilityTimeout: 300 # Wait for 5 minutes after previous attempt fail
      MessageRetentionPeriod: 3600 # Decrease message expire to 1 hours 

  OrderUpdateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, "order-update-queue"]]
      VisibilityTimeout: 300 # Wait for 5 minutes after previous attempt fail
      MessageRetentionPeriod: 3600 # Decrease message expire to 1 hours 
  # ========================== SNS ===================================
  OrderTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Join ["-", [!Ref AWS::StackName, 'order-msg']]
      TopicName: !Join ["-", [!Ref AWS::StackName, 'order-msg']]

  BalanceCheckerSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref OrderTopic
      Endpoint: !GetAtt 
        - BalanceCheckerQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: 'true'

  StockCheckerSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref OrderTopic
      Endpoint: !GetAtt 
        - StockCheckerQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: 'true'

  # ========================== LAMBDA Layer ================================
  OrderModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Join ["-", [!Ref AWS::StackName, "order-modules-layer"]]
      Description: Shared layer to holder common used for Lambdas
      ContentUri: ../lambda-layers/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain


  # ========================== LAMBDA ================================
  OrderAPIGatewayFuntion:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "gateway"]]
      Description: Lambda receives request from API Gateway
      CodeUri: ../lambdas/gateway/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt OrderAPIGatewayRole.Arn
      Architectures:
        - x86_64
      Environment:
        Variables:
          ON_CLOUD: true
          ORDER_TABLE_NAME: !Ref OrderDynamoDBTable
          SNS_TOPIC: !Ref OrderTopic
      Layers:
        - !Ref OrderModulesLayer
      Events:
        AddOrderApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /order
            Method: post
        CaptureOrderApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /orders
            Method: post
        CheckOrderStatusApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /order/{id}/status
            Method: get

  AccountUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "account-update"]]
      Description: Lambda receives request from API Gateway and update account
      CodeUri: ../lambdas/account-update/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt AccountAPIGatewayRole.Arn
      Architectures:
        - x86_64
      Environment:
        Variables:
          ACCOUNT_TABLE_NAME: !Ref AccountDynamoDBTable
          ON_CLOUD: true
      Events:
        AccountApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /account
            Method: post

  BalanceCheckerFunction:
    Type: AWS::Serverless::Function
    DependsOn: BalanceCheckerQueue
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "balancer-checker"]]
      Description: Lambda to ensure customer has sufficient credit
      CodeUri: ../lambdas/balance-checker/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt BalanceCheckerRole.Arn
      Architectures:
        - x86_64
      Layers:
        - !Ref OrderModulesLayer
      Events:
        BalanceCheckSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BalanceCheckerQueue.Arn
            BatchSize: 1      
      Environment:
        Variables:
          ON_CLOUD: true
          ACCOUNT_TABLE_NAME: !Ref AccountDynamoDBTable
          ORDER_UPDATE_QUEUE: !Ref OrderUpdateQueue

  StockUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "stock-update"]]
      Description: Lambda receives request from API Gateway and update stock
      CodeUri: ../lambdas/stock-update/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt StockAPIGatewayRole.Arn
      Architectures:
        - x86_64
      Environment:
        Variables:
          STOCK_TABLE_NAME: !Ref StockDynamoDBTable
          ON_CLOUD: true
      Events:
        StockApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /stock
            Method: post

  StockCheckerFunction:
    Type: AWS::Serverless::Function
    DependsOn: StockCheckerQueue
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "stock-checker"]]
      Description: Lambda to ensure product has sufficient stock
      CodeUri: ../lambdas/stock-checker/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt StockCheckerRole.Arn
      Architectures:
        - x86_64
      Layers:
        - !Ref OrderModulesLayer
      Events:
        StockCheckSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt StockCheckerQueue.Arn
            BatchSize: 1      
      Environment:
        Variables:
          ON_CLOUD: true
          STOCK_TABLE_NAME: !Ref StockDynamoDBTable
          ORDER_UPDATE_QUEUE: !Ref OrderUpdateQueue

  OrderUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "order-update"]]
      Description: Lambda to update order
      CodeUri: ../lambdas/order-update/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt OrderUpdateRole.Arn
      Architectures:
        - x86_64
      Layers:
        - !Ref OrderModulesLayer
      Events:
        StockCheckSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderUpdateQueue.Arn
            BatchSize: 1      
      Environment:
        Variables:
          ON_CLOUD: true
          ORDER_TABLE_NAME: !Ref OrderDynamoDBTable
          SHIP_ORDER_LAMBDA: !Ref ShipOrderFunction

  ShipOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["-", [!Ref AWS::StackName, "ship-order"]]
      Description: Lambda to ship order
      CodeUri: ../lambdas/ship-order/
      Handler: index.handler
      Runtime: nodejs14.x
      Role: !GetAtt ShipOrderRole.Arn
      Architectures:
        - x86_64
      Layers:
        - !Ref OrderModulesLayer
      Environment:
        Variables:
          ON_CLOUD: true
          ORDER_TABLE_NAME: !Ref OrderDynamoDBTable
          ACCOUNT_TABLE_NAME: !Ref AccountDynamoDBTable
          STOCK_TABLE_NAME: !Ref StockDynamoDBTable

  # ========================== DYNAMODB ================================
  OrderDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        !Join ["-", [!Ref AWS::StackName, !Ref OrderTableName, "dynamodb-table"]]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH

  AccountDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        !Join ["-", [!Ref AWS::StackName, "account", "dynamodb-table"]]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH

  StockDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        !Join ["-", [!Ref AWS::StackName, "stock", "dynamodb-table"]]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH

Outputs:
  OrderCaptureStackId:
    Description: "Stack id that generated by SAM"
    Value: !Ref AWS::StackId

  OrderCaptureApi:
    Description: "API Gateway endpoint URL to capture order"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Staging/order/"
      
  OrderTable:
    Description: "Table to store orders"
    Value: !Ref OrderDynamoDBTable
    